# Generated by Django 4.0.3 on 2022-05-22 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_course_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='lesson',
        ),
    ]
