# Generated by Django 4.0.3 on 2022-05-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
        ('classroom', '0003_remove_course_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lesson',
            field=models.ManyToManyField(to='lesson.lesson'),
        ),
    ]
