# Generated by Django 4.0.3 on 2022-05-23 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_course_lesson'),
    ]

    operations = [
    ]
