# Generated by Django 4.0.3 on 2022-05-27 19:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_remove_course_syllabus'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='syllabus',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
