# Generated by Django 4.0.3 on 2022-05-23 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
    ]
