# Generated by Django 4.0.3 on 2022-05-24 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_remove_course_lesson'),
        ('lesson', '0002_auto_20220523_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ManyToManyField(to='classroom.course'),
        ),
    ]
