# Generated by Django 4.0.3 on 2022-05-24 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_lesson_course'),
    ]

    operations = [
    ]
