# Generated by Django 4.0.3 on 2022-05-24 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0005_remove_lesson_course'),
    ]

    operations = [
    ]
