# Generated by Django 4.0.3 on 2022-05-24 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0008_remove_lesson_course_lesson_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
    ]
